#! /bin/bash
##editable configuration
NAME=""
DBname=""
DBuser=""
DBpass=""
SYSTEM="" #joomla | symfony #i will be needing help on this because i dont know permission settings for all frameworks
LocalServerPath="/var/www/html/"$NAME"/"
Excludes=$PWD"/lib/excludes"
WebServerPath="/home/public_html/"
ServerUser=""
ServerIp="111.111.111.111"